version: '2'
volumes:
  dbdata1:

services:
    mysql:
        image: mysql:5.7
        ports:
            - "33061:3306"
        volumes:
            - dbdata1:/var/lib/mysql
        environment:
            - "MYSQL_DATABASE=oscooking"
            - "MYSQL_USER=oscooking"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_ROOT_PASSWORD=secret"

    frontend:
        build:
            context: .
        ports:
            - "3001:3000"
        volumes:
          - /app/node_modules
          - .:/app
          

